#!/usr/bin/env bash
set -e

# update the versions
mvn --settings .github/quarkus-ecosystem-maven-settings.xml -B versions:set-property -Dproperty=quarkus.version -DnewVersion=${QUARKUS_VERSION} -DgenerateBackupPoms=false
mvn --settings .github/quarkus-ecosystem-maven-settings.xml -B versions:set-property -Dproperty=version.io.quarkus -DnewVersion=${QUARKUS_VERSION} -DgenerateBackupPoms=false

# run the tests
mvn --settings .github/quarkus-ecosystem-maven-settings.xml -B clean install -Pquick -pl '!integration-test'

mvn --settings .github/quarkus-ecosystem-maven-settings.xml clean verify -Pjackson-classic -pl integration-test --fail-at-end -e
mvn --settings .github/quarkus-ecosystem-maven-settings.xml clean verify -Pjsonb-classic -pl integration-test --fail-at-end -e
mvn --settings .github/quarkus-ecosystem-maven-settings.xml clean verify -Pjackson-reactive -pl integration-test --fail-at-end -e
mvn --settings .github/quarkus-ecosystem-maven-settings.xml clean verify -Pjsonb-reactive -pl integration-test --fail-at-end -e