#!/bin/bash

java_ver=$(java -version 2>&1 | head -1 | cut -d'"' -f2 | sed '/^1\./s///' | cut -d'.' -f1)

if [[ "$java_ver" != "17" ]]; then
  read -p "Expected Java version is 17, while $java_ver was found. Switch to java 17 (y/n)? " choice
  if [[ "$choice" != "y" ]]; then
    exit;
  fi

  echo "Switching java version to 17"
  export JAVA_HOME=$(/usr/libexec/java_home -v 17);
fi

set -e
set -x

./mvnw clean install -Pquick

./mvnw clean verify -P it,native,jackson-classic -pl 'integration-test/core,integration-test/rest-client'
./mvnw clean verify -P it,native,jsonb-classic -pl 'integration-test/core,integration-test/rest-client'
./mvnw clean verify -P it,native,jackson-reactive -pl 'integration-test/core,integration-test/rest-client'
./mvnw clean verify -P it,native,jsonb-reactive -pl 'integration-test/core,integration-test/rest-client'
./mvnw clean verify -P it,native -pl 'integration-test/openapi,integration-test/zalando,integration-test/rest-client'