# This workflow will build and deploy a snapshot of your artifact to Sonatype Snapshots repository
name: Deploy Snapshots

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true
on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  deploy-snapshot:
    runs-on: ubuntu-latest
    name: Deploy Snapshot artifacts
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'
          server-id: 'ossrh'
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Deploy Snapshot
        run: |
          mvn -B clean deploy -DperformRelease=true -Drelease -Pquick -pl '!integration-test'
        env:
            MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
            MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
            MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
